### PR TITLE
Remove code for building against 4.3 and unused function parameter 

### PR DESCRIPTION
**Pull request by dhickin**
<p>I've removed code for building against the EPICS 4.3.0.</p>

<p>This code was conditionally compiled using the preprocessor macro PVA_API_VERSION. The
code no longer builds against 4.3.0 since the addition of unions, the 4.3.0 API is now very old, both for pvData and pvAccess, and now that the PVStructure::get*Field functions deprecated since 4.4 have been removed it would be burdensome to make it build against 4.3.0 again.</p>

<p>I've also removed the code for conditionally compiling against old version of the RPC API. PVA_API_VERSION as these will only be applicable for building against pre-4.4.0 versions.Specifically the code conditionally-compiled when the PVA_API_RPC_VERSION is 430 or 435. </p>

<p>With the get*Field operations removed pyListToScalarArrayField no longer need the scalarType parameter. I kept this because the 4.3 version of the code was using it, but with the 4.3 code it can go.</p>

### CODE REVIEW

**Comment by dhickin** [comment]
<p>Does anyone understand why this automated build failed? It says:</p>

<p><q>checking for usable EPICS4 libraries for Linux OS (gcc compiler) and host architecture linux-x86_64... no
configure: error: could not compile and link EPICS4 test code: check your EPICS4 installation
make: **\* [configure] Error 1checking for usable EPICS4 libraries for Linux OS (gcc compiler) and host architecture linux-x86_64... no
configure: error: could not compile and link EPICS4 test code: check your EPICS4 installation
make: **\* [configure] Error 1
Build step 'Execute shell' marked build as failure
An attempt to send an e-mail to empty list of recipients, ignored.</q><p>

**Comment by ralphlange** [comment]
Some autotools m4 magic going wrong. Look in tools/autoconf/m4.
_Finite Incantatem!_

**Comment by sveseli** [comment]
Configure code is failing because it cannot find pvaClient.h. 

configure:4925: g++ -o conftest -g -O2   -I/tmp/stuff/include -I/tmp/stuff/include/os/Linux -I/tmp/stuff/include/compiler/gcc -I/tmp/stuff/include -I/tmp/stuff/include -I/tmp/stuff/include -I/tmp/stuff/include   -L/tmp/stuff/lib/linux-x86_64 -L/tmp/stuff/lib/linux-x86_64 -L/tmp/stuff/lib/linux-x86_64 -L/tmp/stuff/lib/linux-x86_64 -L/tmp/stuff/lib/linux-x86_64 conftest.cpp -lpvData -lpvAccess -lnt -lpvaClient -lCom >&5
conftest.cpp:19:38: fatal error: pv/pvaClient.h: No such file or directory
compilation terminated.

**Comment by anjohnson** [comment]
This module needs to built against both pvaClientCPP and normativeTypesCPP, which don't appear to be mentioned in the cloudbees_build script at all. If the configure script doesn't find them it assumes it is being built against an earlier API version, so the build could still succeed. This merge may have removed the old API, so it now fails (that's my guess anyway).

Sinisa, could you modify the ax_epics4.m4 file to show a separate "checking for ..." message for the pvaClientCPP and normativeTypesCPP modules to make the configure output more obvious as to what's missing when it does fail? My autoconf-foo isn't yet strong enough to know exactly where to make that change myself.

**Comment by anjohnson** [comment]
Hmm, adding the pvaClient and normativeTypes code didn't help, although it does give a different error now:

```
configure:4925: g++ -o conftest -g -O2   -I/tmp/stuff/include -I/tmp/stuff/include/os/Linux -I/tmp/stuff/include/compiler/gcc -I/tmp/stuff/include -I/tmp/stuff/include -I/tmp/stuff/include -I/tmp/stuff/include   -L/tmp/stuff/lib/linux-x86_64 -L/tmp/stuff/lib/linux-x86_64 -L/tmp/stuff/lib/linux-x86_64 -L/tmp/stuff/lib/linux-x86_64 -L/tmp/stuff/lib/linux-x86_64 conftest.cpp -lpvData -lpvAccess -lnt -lpvaClient -lCom >&5
/tmp/stuff/lib/linux-x86_64/libpvAccess.so: undefined reference to 'epics::pvData::PVStructure::getScalarArrayField(std::string const&, epics::pvData::ScalarType)'
```

Any ideas? I can't seem to find the `getScalarArrayField()` method anywhere — was this one that David removed? If so the ax_epics4.m4 script needs fixing, but how come this test still succeeds on the APS Jenkins but fails on Cloudbees?

**Comment by ralphlange** [comment]
retest this please

**Comment by anjohnson** [comment]
Thanks Ralph, your fix explained what was going on that had me stumped.

**Pull request merged**
